<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<!-- This is a comment outside the root-Element: After that we have a doctype
declaration, and some notations -->
<!DOCTYPE root PUBLIC "hello" "foo" [
    <!-- A doctype declaration may contain: element declarations, attribute
    list declarations, entity reference declarations, notation declarations,
    processing instructions, and comments (like this one) -->
    <?foobar ?>
    <!ELEMENT root ANY>
    <!ELEMENT container-element
    (#PCDATA|inline-element|container-element|empty-element)*>
    <!ELEMENT inline-element (#PCDATA)>
    <!ENTITY attributes "Attributes">
    <!ELEMENT empty-element EMPTY>
    <!ATTLIST container-element attribute1 CDATA #IMPLIED>
    <!ATTLIST container-element attribute2 CDATA #IMPLIED>
    <!ATTLIST inline-element attribute1 CDATA #IMPLIED>
    <!ATTLIST inline-element attribute2 CDATA #IMPLIED>
    <!NOTATION Foo SYSTEM "foo">
]>
<root>
    <!-- Single line comment -->
    <empty-element/>
    <empty-element/>
    <empty-element/>
    foo
    <container-element>
        <inline-element>foo</inline-element>
    </container-element>
    <!-- Multiple line comment: Just because. -->
    <container-element>
        <container-element>
            But this is an <inline-element>inline-element</inline-element>,
            which should not cause a line break.
        </container-element>
    </container-element>
    <container-element attribute1="value1" attribute2="value2">
        Now with attributes, because <inline-element attribute1="value1"
        attribute2="value2">Attributes</inline-element> often cause line
        breaks.
    </container-element>
    <container-element>
        This inline-<inline-element>ele</inline-element>ment has no spaces
        around.
    </container-element>
    <?a-random-processing-instruction "foo"?>
    <inline-element>foo</inline-element>
    <![CDATA[Here comes a small CDATA section]]>
    <inline-element>foo</inline-element>
    <container-element>
        Yet another container-element having a
        <!-- comment -->
        <inline-element>foo</inline-element> inside, an
        <empty-element/>
        and a
        <![CDATA[Here comes <hi>another</hi> CDATA section]]>
        <inline-element>foo</inline-element>.
    </container-element>
</root>